<?php 
$realm = new Application_Model_Realm();
$championMapper = new Application_Model_ChampionMapper();
$spellMapper = new Application_Model_SpellMapper();
$itemMapper = new Application_Model_ItemMapper();
?>
<div class="sum-title grid_12">
    <img class="sum-icon" src="<?php echo $this->baseUrl() . $this->sumMapper->getProfileIcon($this->summoner['profileIconId'], $realm) ; ?>" alt="<?php echo $this->summoner['name']; ?>" />
    <h2><?php echo $this->summoner['name']; ?></h2>
    <h4><em>Nv: <?php echo $this->summoner['summonerLevel']; ?></em> <span><?php $rank = ($this->league) ? $this->league['tier'] . ' ' . $this->league['sumData']['division'] : 'UNRANKED'; echo $rank; ?></span></h4>
</div>
<br class="clear" />
<div id="view-content" class="prefix_3 grid_3 suffix_3" style="height: 280px;">
    <div style="background-color: #FFD; height: 100%;">
    <?php if($this->league): ?>
        <?php echo $rank; ?><br />
        <?php echo $this->league['sumData']['leaguePoints'] . ' points'; ?><br />
        <?php echo $this->league['sumData']['wins'] . ' wins'; ?><br />
        <?php echo $this->league['sumData']['losses'] . ' losses'; ?><br />
    <?php else: ?>
        &nbsp;
    <?php endif; ?>
    </div>
</div>
<div class="grid_3" style="height: 280px; background-color: #FFD;">
    &nbsp;
</div>
<br class="clear" />
<div class="sum-last-games grid_12">
    <h3>Últimos Jogos</h3>
    <br class="clear" />
    <style type="text/css">
        .sum-item-img {width: 20px; height: 20px;}
    </style>
    <table class="sum-game">
        <?php foreach($this->games['games'] as $game): ?>
        <tr<?php $result = ($game['stats']['win']) ? 'win' : 'loss'; echo ' class="' . $result . '"'; ?>>
            <td>
                <a href="<?php echo $this->url(array('id' => $game['championId']), 'champion', true); ?>">
                    <img class="champ-square-info" src="<?php echo $this->baseUrl() . $championMapper->getChampionSquareImg($game['championId'], $realm); ?>" alt="" />
                </a>
                <img class="champ-game-spell" src="<?php echo $spellMapper->getImage($game['spell1'], $realm); ?>" alt="spell #1" />
                <img class="champ-game-spell" src="<?php echo $spellMapper->getImage($game['spell2'], $realm); ?>" alt="spell #2" />
            </td>
            <td>
                <span class="champ-info-stats"><em><?php echo $this->DisplayGameSubType($game['subType']); ?></em> - <strong>K/D/A:</strong> <?php echo isset($game['stats']['championsKilled']) ? $game['stats']['championsKilled'] : 0 ; ?>/<?php echo isset($game['stats']['numDeaths']) ? $game['stats']['numDeaths'] : 0 ; ?>/<?php echo isset($game['stats']['assists']) ? $game['stats']['assists'] : 0 ; ?> - <strong>CS:</strong> <?php @print $this->DisplayCS($game['stats']['minionsKilled'], $game['stats']['neutralMinionsKilled']); ?> - <strong>Nv:</strong> <?php echo $game['stats']['level']; ?></span>
            </td>
            <?php if(isset($game['fellowPlayers'])): ?>
            <td>
                <?php foreach($game['fellowPlayers'] as $fellow): ?>
                <?php if($fellow['teamId'] == $game['teamId']): ?>
                <a href="<? echo $this->url(array('region' => $this->region, 'id' => $fellow['summonerId']),"summoner",true); ?>"><img class="champ-fellow-square" src="<?php echo $this->baseUrl() . $championMapper->getChampionSquareImg($fellow['championId'], $realm); ?>" alt="champ" /></a>
                <?php endif; ?>
                <?php endforeach; ?>
            </td>
            <?php else: ?>
            <td>&nbsp;</td>
            <?php endif; ?>
            <td>
                <table style="display: inline-block;">
                    <tr>
                        <?php for($i=0;$i<=5;$i++): ?>
                        <td>
                        <?php if(isset($game["stats"]["item$i"])): ?>
                            <img class="sum-item-img" src="<?php echo $this->baseUrl() . $itemMapper->getImage($game["stats"]["item$i"], $realm); ?>" alt="item <?php echo $i; ?>" />
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                        </td>
                        <?php if($i == 2) echo "</tr><tr>"; ?>
                        <?php endfor; ?>
                    </tr>
                </table>
                <table style="display: inline-block;">
                    <tr>
                        <td>
                            <?php if(isset($game["stats"]["item6"])): ?>
                            <img class="sum-item-img" src="<?php echo $this->baseUrl() . $itemMapper->getImage($game["stats"]["item$i"], $realm); ?>" alt="item <?php echo $i; ?>" />
                            <?php else: ?>
                            &nbsp;
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </td>
            <td>Gold: <?php echo $game['stats']['goldEarned']; ?></td>
            <td>
                <?php $dt = Zend_Date::now(); $dt->setTimestamp(($game['createDate']/1000)); ?>
                <span class="champ-info-time"><strong>Data:</strong> <?php echo $dt->get('dd/MM/yyyy'); ?> - <strong>Duração:</strong> <?php echo $this->DisplayDuration($game['stats']['timePlayed']); ?></span>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <br class="clear" />
</div>